// exam-archive.js — পরীক্ষার তালিকা
// প্রতিটা exam-এর id, job-solution.js এর id prefix-এর সাথে মিলতে হবে।

const EXAM_ARCHIVE = [
  {
    id: "job-2025-dc",
    ministry: "জেলা প্রশাসকের কার্যালয়, জয়পুরহাট",
    post: "নাজির কাম ক্যাশিয়ার / সার্টিফিকেট পেশকার",
    date: "2025-06-27",
    duration: "৯০ মিনিট",
    totalMarks: 105,
    totalQuestions: 18,
  },
  {
    id: "job-2025-tech-edu-keeper",
    ministry: "কারিগরি শিক্ষা অধিদপ্তর",
    post: "সহকারী কাম কিপার",
    date: "2025-07-04",
    duration: "৯০ মিনিট",
    totalMarks: 113,
    totalQuestions: 34,
  },
  {
    id: "job-2025-tech-edu-driver",
    ministry: "কারিগরি শিক্ষা অধিদপ্তর",
    post: "ড্রাইভার কাম মেকানিক",
    date: "2025-07-04",
    duration: "৯০ মিনিট",
    totalMarks: 97,
    totalQuestions: 34,
  },
  {
    id: "job-2025-tech-edu-steno",
    ministry: "কারিগরি শিক্ষা অধিদপ্তর",
    post: "সাঁটলিপিকার কাম-কম্পিউটার অপারেটর",
    date: "2025-07-04",
    duration: "৯০ মিনিট",
    totalMarks: 104,
    totalQuestions: 34,
  },
  {
    id: "job-2025-iwta-traffic",
    ministry: "অভ্যন্তরীণ নৌ পরিবহন কর্তৃপক্ষ",
    post: "ট্রাফিক সুপারভাইজার",
    date: "2025-07-04",
    duration: "৯০ মিনিট",
    totalMarks: 70,
    totalQuestions: 6,
  },
  {
    id: "job-2025-dc-bhola",
    ministry: "জেলা প্রশাসকের কার্যালয়, ভোলা",
    post: "অফিস সহায়ক/নিরাপত্তা প্রহরী",
    date: "2025-07-05",
    duration: "৮০ মিনিট",
    totalMarks: 80,
    totalQuestions: 20,
  },
  {
    id: "job-2025-coast-guard-uhs",
    ministry: "বাংলাদেশ কোস্ট গার্ড",
    post: "উচ্চমান সহকারী",
    date: "2025-07-05",
    duration: "৯০ মিনিট",
    totalMarks: 67,
    totalQuestions: 12,
  },
  {
    id: "job-2025-navy-office",
    ministry: "বাংলাদেশ নৌ বাহিনী",
    post: "অফিস সহকারী কাম-কম্পিউটার অপারেটর",
    date: "2025-07-11",
    duration: "৯০ মিনিট",
    totalMarks: 86,
    totalQuestions: 28,
  },
  {
    id: "job-2025-coast-guard-support",
    ministry: "বাংলাদেশ কোস্ট গার্ড",
    post: "অফিস সহায়ক",
    date: "2025-07-12",
    duration: "৬০ মিনিট",
    totalMarks: 69,
    totalQuestions: 13,
  },
  {
    id: "job-2025-hbfc-data-entry",
    ministry: "বাংলাদেশ হাউজ বিল্ডিং ফাইন্যান্স কর্পোরেশন",
    post: "ডাটা এন্ট্রি অপারেটর",
    date: "2025-07-18",
    duration: "৬০ মিনিট",
    totalMarks: 60,
    totalQuestions: 10,
  },
  // ══════════════════════════════════════════════════════════
  // সোর্স: self_job_solution_330-370_page (পৃষ্ঠা ৩৩০-৩৭০)
  // ══════════════════════════════════════════════════════════
  {
    id: "job-2025-prison-teacher",
    ministry: "কারা অধিদপ্তর",
    post: "শিক্ষক",
    date: "2025-09-05",
    duration: "৯০ মিনিট",
    totalMarks: 85,
    totalQuestions: 14,
  },
  {
    id: "job-2025-tech-madrasah-office-asst",
    ministry: "কারিগরি ও মাদ্রাসা শিক্ষা বিভাগ",
    post: "অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-09-05",
    duration: "৯০ মিনিট",
    totalMarks: 90,
    totalQuestions: 23,
  },
  {
    id: "job-2025-bof-tech-helper",
    ministry: "বাংলাদেশ সমরাস্ত্র কারখানা (বিওএফ)",
    post: "টেকনিক্যাল হেলপার",
    date: "2025-09-12",
    duration: "৬০ মিনিট",
    totalMarks: 40,
    totalQuestions: 13,
  },
  {
    id: "job-2025-coast-guard-support-sep",
    ministry: "বাংলাদেশ কোস্ট গার্ড",
    post: "অফিস সহায়ক",
    date: "2025-09-12",
    duration: "৬০ মিনিট",
    totalMarks: 70,
    totalQuestions: 13,
  },
  {
    id: "job-2025-prison-computer-typist",
    ministry: "কারা অধিদপ্তর",
    post: "কারা সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-09-19",
    duration: "৯০ মিনিট",
    totalMarks: 84,
    totalQuestions: 16,
  },
  {
    id: "job-2025-bof-technician",
    ministry: "বাংলাদেশ সমরাস্ত্র কারখানা (বিওএফ)",
    post: "টেকনিশিয়ান",
    date: "2025-09-19",
    duration: "৬০ মিনিট",
    totalMarks: 72,
    totalQuestions: 20,
  },
  {
    id: "job-2025-vehicle-maintenance-store-keeper",
    ministry: "যানবাহন ও যন্ত্রপাতি রক্ষণাবেক্ষণ সংস্থা",
    post: "স্টোর কিপার",
    date: "2025-09-20",
    duration: "৯০ মিনিট",
    totalMarks: 80,
    totalQuestions: 28,
  },
  {
    id: "job-2025-dc-manikganj",
    ministry: "জেলা প্রশাসকের কার্যালয়, মানিকগঞ্জ",
    post: "অফিস সহায়ক",
    date: "2025-09-26",
    duration: "৬০ মিনিট",
    totalMarks: 75,
    totalQuestions: 28,
  },
  {
    id: "job-2025-erd-office-sohayok",
    ministry: "অর্থনৈতিক সম্পর্ক বিভাগ",
    post: "অফিস সহায়ক",
    date: "2025-07-26",
    duration: "৬০ মিনিট",
    totalMarks: 40,
    totalQuestions: 13,
  },
  {
    id: "job-2025-erd-steno-typist",
    ministry: "অর্থনৈতিক সম্পর্ক বিভাগ",
    post: "সাঁট মুদ্রাক্ষরিক কাম-কম্পিউটার অপারেটর",
    date: "2025-09-26",
    duration: "৯০ মিনিট",
    totalMarks: 90,
    totalQuestions: 26,
  },
  {
    id: "job-2025-health-service-office-asst",
    ministry: "স্বাস্থ্য সেবা বিভাগ",
    post: "অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-09-26",
    duration: "৯০ মিনিট",
    totalMarks: 85,
    totalQuestions: 15,
  },
  {
    id: "job-2025-barc-head-assistant",
    ministry: "বাংলাদেশ কৃষি গবেষণা কাউন্সিল",
    post: "প্রধান সহকারী",
    date: "2025-10-04",
    duration: "৯০ মিনিট",
    totalMarks: 75,
    totalQuestions: 13,
  },
  {
    id: "job-2025-div-comm-ctg-office-sohayok",
    ministry: "বিভাগীয় কমিশনারের কার্যালয়, চট্টগ্রাম",
    post: "অফিস সহায়ক",
    date: "2025-10-11",
    duration: "৬০ মিনিট",
    totalMarks: 40,
    totalQuestions: 17,
  },
  {
    id: "job-2025-div-comm-ctg-record-keeper",
    ministry: "বিভাগীয় কমিশনারের কার্যালয়, চট্টগ্রাম",
    post: "রেকর্ড কিপার",
    date: "2025-10-11",
    duration: "৯০ মিনিট",
    totalMarks: 100,
    totalQuestions: 18,
  },
  {
    id: "job-2025-div-comm-ctg-office-asst",
    ministry: "বিভাগীয় কমিশনারের কার্যালয়, চট্টগ্রাম",
    post: "অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-10-11",
    duration: "৯০ মিনিট",
    totalMarks: 100,
    totalQuestions: 18,
  },
  {
    id: "job-2025-nbr-steno-typist",
    ministry: "জাতীয় রাজস্ব বোর্ড",
    post: "সাঁটমুদ্রাক্ষরিক কাম-কম্পিউটার অপারেটর",
    date: "2025-10-11",
    duration: "৯০ মিনিট",
    totalMarks: 70,
    totalQuestions: 16,
  },
  {
    id: "job-2025-bof-office-asst-typist",
    ministry: "বাংলাদেশ সমরাস্ত্র কারখানা (বিওএফ)",
    post: "অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-10-17",
    duration: "৯০ মিনিট",
    totalMarks: 70,
    totalQuestions: 26,
  },
  {
    id: "job-2025-barc-maintenance-inspector",
    ministry: "বাংলাদেশ কৃষি গবেষণা কাউন্সিল",
    post: "রক্ষণাবেক্ষণ পরিদর্শক",
    date: "2025-10-17",
    duration: "৬০ মিনিট",
    totalMarks: 75,
    totalQuestions: 8,
  },
  {
    id: "job-2025-dc-netrokona",
    ministry: "জেলা প্রশাসকের কার্যালয়, নেত্রকোণা",
    post: "অফিস সহায়ক",
    date: "2025-11-21",
    duration: "৬০ মিনিট",
    totalMarks: 109,
    totalQuestions: 37,
  },
  {
    id: "job-2025-textile-office-sohayok",
    ministry: "বস্ত্র অধিদপ্তর",
    post: "অফিস সহায়ক",
    date: "2025-11-29",
    duration: "৬০ মিনিট",
    totalMarks: 90,
    totalQuestions: 25,
  },
  {
    id: "job-2025-supreme-court-office-asst",
    ministry: "বাংলাদেশ সুপ্রীম কোর্ট",
    post: "অফিস সহকারী",
    date: "2025-11-29",
    duration: "৯০ মিনিট",
    totalMarks: 80,
    totalQuestions: 11,
  },
  {
    id: "job-2025-dc-lalmonirhat",
    ministry: "জেলা প্রশাসকের কার্যালয়, লালমনিরহাট",
    post: "অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-12-04",
    duration: "৯০ মিনিট",
    totalMarks: 108,
    totalQuestions: 16,
  },
  {
    id: "job-2025-air-force-office-sohayok",
    ministry: "বিমান বাহিনী সদর দপ্তর",
    post: "অফিস সহায়ক ও বিভিন্ন",
    date: "2025-12-06",
    duration: "৯০ মিনিট",
    totalMarks: 69,
    totalQuestions: 12,
  },
  {
    id: "job-2025-heart-institute-telephone-op",
    ministry: "জাতীয় হৃদরোগ ইনস্টিটিউট ও হাসপাতাল",
    post: "টেলিফোন অপারেটর",
    date: "2025-12-06",
    duration: "৯০ মিনিট",
    totalMarks: 120,
    totalQuestions: 15,
  },
  {
    id: "job-2025-judicial-service-office-sohayok",
    ministry: "বাংলাদেশ জুডিসিয়াল সার্ভিস কমিশন",
    post: "অফিস সহায়ক",
    date: "2025-12-06",
    duration: "৯০ মিনিট",
    totalMarks: 90,
    totalQuestions: 8,
  },
  {
    id: "job-2025-land-survey-peshkar",
    ministry: "ভূমি রেকর্ড ও জরিপ অধিদপ্তর",
    post: "পেশকার",
    date: "2025-12-12",
    duration: "৯০ মিনিট",
    totalMarks: 139,
    totalQuestions: 17,
  },
  {
    id: "job-2025-judicial-service-steno",
    ministry: "বাংলাদেশ জুডিসিয়াল সার্ভিস কমিশন",
    post: "সাঁটমুদ্রাক্ষরিক-কাম-কম্পিউটার অপারেটর",
    date: "2025-12-13",
    duration: "৯০ মিনিট",
    totalMarks: 87,
    totalQuestions: 8,
  },
  {
    id: "job-2025-mopa-data-entry-control",
    ministry: "জনপ্রশাসন মন্ত্রণালয়",
    post: "ডাটা এন্ট্রি/কন্ট্রোল অপারেটর",
    date: "2025-08-01",
    duration: "৯০ মিনিট",
    totalMarks: 90,
    totalQuestions: 13,
  },
  {
    id: "job-2025-mopa-account-keeper",
    ministry: "জনপ্রশাসন মন্ত্রণালয়",
    post: "হিসাব রক্ষক",
    date: "2025-08-01",
    duration: "৯০ মিনিট",
    totalMarks: 80,
    totalQuestions: 14,
  },
  {
    id: "job-2025-niport-head-assistant",
    ministry: "জাতীয় জনসংখ্যা গবেষণা ও প্রশিক্ষণ ইনস্টিটিউট (NIPORT)",
    post: "প্রধান সহকারী",
    date: "2025-08-01",
    duration: "৯০ মিনিট",
    totalMarks: 70,
    totalQuestions: 12,
  },
  {
    id: "job-2025-dc-sunamganj-account-asst",
    ministry: "জেলা প্রশাসকের কার্যালয়, সুনামগঞ্জ",
    post: "হিসাব সহকারী",
    date: "2025-08-08",
    duration: "৯০ মিনিট",
    totalMarks: 102,
    totalQuestions: 13,
  },
  {
    id: "job-2025-niport-office-sohayok",
    ministry: "জাতীয় জনসংখ্যা গবেষণা ও প্রশিক্ষণ ইনস্টিটিউট (NIPORT)",
    post: "অফিস সহায়ক",
    date: "2025-08-08",
    duration: "৬০ মিনিট",
    totalMarks: 64,
    totalQuestions: 13,
  },
  {
    id: "job-2025-health-edu-data-entry",
    ministry: "স্বাস্থ্য শিক্ষা অধিদপ্তর",
    post: "ডাটা এন্ট্রি কাম কম্পিউটার অপারেটর",
    date: "2025-08-08",
    duration: "৯০ মিনিট",
    totalMarks: 68,
    totalQuestions: 13,
  },
  {
    id: "job-2025-bof-junior-technician",
    ministry: "বাংলাদেশ সমরাস্ত্র কারখানা (বিওএফ)",
    post: "জুনিয়র টেকনিশিয়ান",
    date: "2025-08-08",
    duration: "৯০ মিনিট",
    totalMarks: 66,
    totalQuestions: 15,
  },
  {
    id: "job-2025-mopa-office-sohayok",
    ministry: "জনপ্রশাসন মন্ত্রণালয়",
    post: "অফিস সহায়ক",
    date: "2025-08-09",
    duration: "৬০ মিনিট",
    totalMarks: 72,
    totalQuestions: 10,
  },
  {
    id: "job-2025-food-dept-mechanical-foreman",
    ministry: "খাদ্য অধিদপ্তর",
    post: "মেকানিক্যাল ফোরম্যান ও অন্যান্য",
    date: "2025-08-09",
    duration: "৯০ মিনিট",
    totalMarks: 112,
    totalQuestions: 19,
  },
  {
    id: "job-2025-food-dept-electrical-foreman",
    ministry: "খাদ্য অধিদপ্তর",
    post: "ইলেকট্রিক্যাল ফোরম্যান ও ইলেকট্রিশিয়ান",
    date: "2025-08-09",
    duration: "৯০ মিনিট",
    totalMarks: 109,
    totalQuestions: 19,
  },
  {
    id: "job-2025-nlasp-office-asst-typist",
    ministry: "জাতীয় আইনগত সহায়তা প্রদান সংস্থা",
    post: "অফিস সহকারী কাম-কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-10-18",
    duration: "৯০ মিনিট",
    totalMarks: 66,
    totalQuestions: 8,
  },
  {
    id: "job-2025-nlasp-bench-asst",
    ministry: "জাতীয় আইনগত সহায়তা প্রদান সংস্থা",
    post: "বেঞ্চ সহকারী",
    date: "2025-10-18",
    duration: "৯০ মিনিট",
    totalMarks: 80,
    totalQuestions: 8,
  },
  {
    id: "job-2025-islamic-foundation-office-asst",
    ministry: "ইসলামিক ফাউন্ডেশন",
    post: "অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-10-24",
    duration: "৯০ মিনিট",
    totalMarks: 69,
    totalQuestions: 21,
  },
  {
    id: "job-2025-dpe-accountant",
    ministry: "প্রাথমিক শিক্ষা অধিদপ্তর",
    post: "উচ্চমান সহকারী কাম হিসাবরক্ষক",
    date: "2025-10-24",
    duration: "৯০ মিনিট",
    totalMarks: 83,
    totalQuestions: 21,
  },
  {
    id: "job-2025-dpe-store-keeper",
    ministry: "প্রাথমিক শিক্ষা অধিদপ্তর",
    post: "ভান্ডার রক্ষক",
    date: "2025-10-24",
    duration: "৯০ মিনিট",
    totalMarks: 83,
    totalQuestions: 19,
  },
  {
    id: "job-2025-biwta-store-officer",
    ministry: "বাংলাদেশ অভ্যন্তরীন নৌ-পরিবহন কর্তৃপক্ষ",
    post: "ভান্ডারী",
    date: "2025-10-24",
    duration: "৬০ মিনিট",
    totalMarks: 50,
    totalQuestions: 6,
  },
  {
    id: "job-2025-health-services-office-sohayak",
    ministry: "স্বাস্থ্য সেবা বিভাগ",
    post: "অফিস সহায়ক",
    date: "2025-10-24",
    duration: "৬০ মিনিট",
    totalMarks: 77,
    totalQuestions: 15,
  },
  {
    id: "job-2025-dc-narayanganj-nazir-cashier",
    ministry: "জেলা প্রশাসকের কার্যালয়, নারায়ণগঞ্জ",
    post: "নাজির কাম ক্যাশিয়ার, অফিস সহকারী",
    date: "2025-10-24",
    duration: "৯০ মিনিট",
    totalMarks: 126,
    totalQuestions: 16,
  },
  {
    id: "job-2025-navy-artificer",
    ministry: "প্রতিরক্ষা মন্ত্রণালয় (বাংলাদেশ নৌবাহিনী)",
    post: "আর্টিফিসার",
    date: "2025-10-25",
    duration: "১২০ মিনিট",
    totalMarks: 120,
    totalQuestions: 16,
  },
  {
    id: "job-2025-health-nimu-tc-uccho-man-sohokari",
    ministry: "স্বাস্থ্য সেবা বিভাগ এর নিমিউ এন্ড টিসি",
    post: "উচ্চমান সহকারী",
    date: "2025-10-17",
    duration: "৯০ মিনিট",
    totalMarks: 74,
    totalQuestions: 12,
  },
  {
    id: "job-2025-railway-office-asst-typist",
    ministry: "রেলপথ মন্ত্রণালয়",
    post: "অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-10-18",
    duration: "৯০ মিনিট",
    totalMarks: 90,
    totalQuestions: 15,
  },
  {
    id: "job-2025-dmch-computer-operator",
    ministry: "ঢাকা মেডিকেল কলেজ হাসপাতাল",
    post: "কম্পিউটার অপারেটর",
    date: "2025-10-31",
    duration: "৯০ মিনিট",
    totalMarks: 98,
    totalQuestions: 15,
  },
  {
    id: "job-2025-dphe-rangamati-office-asst-typist",
    ministry: "জনস্বাস্থ্য প্রকৌশলী অধিদপ্তর, রাঙ্গামাটি",
    post: "অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-10-31",
    duration: "৯০ মিনিট",
    totalMarks: 89,
    totalQuestions: 14,
  },
  {
    id: "job-2025-land-appeal-board-office-sohayok",
    ministry: "ভূমি আপীল বোর্ড",
    post: "অফিস সহায়ক",
    date: "2025-11-14",
    duration: "৬০ মিনিট",
    totalMarks: 86,
    totalQuestions: 19,
  },
  {
    id: "job-2025-biddyut-office-sohayok",
    ministry: "বিদ্যুৎ বিভাগ",
    post: "অফিস সহায়ক",
    date: "2025-11-14",
    duration: "৬০ মিনিট",
    totalMarks: 50,
    totalQuestions: 11,
  },
  {
    id: "job-2025-biddyut-steno-typist",
    ministry: "বিদ্যুৎ বিভাগ",
    post: "সাঁটমুদ্রাক্ষরিক কাম কম্পিউটার অপারেটর",
    date: "2025-11-14",
    duration: "৯০ মিনিট",
    totalMarks: 81,
    totalQuestions: 16,
  },
  {
    id: "job-2025-biddyut-office-asst-typist",
    ministry: "বিদ্যুৎ বিভাগ",
    post: "অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-11-14",
    duration: "৯০ মিনিট",
    totalMarks: 83,
    totalQuestions: 16,
  },
  {
    id: "job-2025-immigration-passport-office-asst-typist",
    ministry: "ইমিগ্রেশন ও পাসপোর্ট অধিদপ্তর",
    post: "অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-11-14",
    duration: "৯০ মিনিট",
    totalMarks: 73,
    totalQuestions: 16,
  },
  {
    id: "job-2025-primary-mass-edu-office-asst-typist",
    ministry: "প্রাথমিক ও গণশিক্ষা মন্ত্রণালয়",
    post: "অফিস সহকারী কাম-কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-11-21",
    duration: "৯০ মিনিট",
    totalMarks: 98,
    totalQuestions: 17,
  },
  {
    id: "job-2025-primary-mass-edu-steno-typist",
    ministry: "প্রাথমিক ও গণশিক্ষা মন্ত্রণালয়",
    post: "সাঁট-মুদ্রাক্ষরিক কাম-কম্পিউটার অপারেটর",
    date: "2025-11-21",
    duration: "৯০ মিনিট",
    totalMarks: 95,
    totalQuestions: 16,
  },
  {
    id: "job-2025-primary-mass-edu-office-sohayok",
    ministry: "প্রাথমিক ও গণশিক্ষা মন্ত্রণালয়",
    post: "অফিস সহায়ক",
    date: "2025-11-21",
    duration: "৬০ মিনিট",
    totalMarks: 79,
    totalQuestions: 21,
  },
  {
    id: "job-2025-pwd-office-asst-typist",
    ministry: "গণপূর্ত অধিদপ্তর",
    post: "অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-12-19",
    duration: "৯০ মিনিট",
    totalMarks: 72,
    totalQuestions: 31,
  },
  {
    id: "job-2025-pwd-shorthand-typist",
    ministry: "গণপূর্ত অধিদপ্তর",
    post: "সাঁট-মুদ্রাক্ষরিক কাম কম্পিউটার অপারেটর",
    date: "2025-12-19",
    duration: "৯০ মিনিট",
    totalMarks: 69,
    totalQuestions: 30,
  },
  {
    id: "job-2025-pwd-office-sohayok",
    ministry: "গণপূর্ত অধিদপ্তর",
    post: "অফিস সহায়ক",
    date: "2025-12-19",
    duration: "৯০ মিনিট",
    totalMarks: 67,
    totalQuestions: 27,
  },
  {
    id: "job-2025-pwd-designer",
    ministry: "গণপূর্ত অধিদপ্তর",
    post: "নকশাকার",
    date: "2025-12-19",
    duration: "৯০ মিনিট",
    totalMarks: 66.6,
    totalQuestions: 24,
  },
  {
    id: "job-2025-labour-ministry-bench-asst",
    ministry: "শ্রম ও কর্মসংস্থান মন্ত্রণালয়",
    post: "বেঞ্চ সহকারী",
    date: "2025-12-19",
    duration: "৯০ মিনিট",
    totalMarks: 65,
    totalQuestions: 12,
  },
  {
    id: "job-2025-lgd-shorthand-typist",
    ministry: "স্থানীয় সরকার বিভাগ",
    post: "সাঁট মুদ্রাক্ষরিক কাম কম্পিউটার অপারেটর",
    date: "2025-12-19",
    duration: "৯০ মিনিট",
    totalMarks: 68.4,
    totalQuestions: 17,
  },
  {
    id: "job-2025-ncc-sub-asst-engineer-civil",
    ministry: "নারায়ণগঞ্জ সিটি কর্পোরেশন",
    post: "উপ সহকারী প্রকৌশলী (সিভিল)",
    date: "2025-12-22",
    duration: "৯০ মিনিট",
    totalMarks: 52.5,
    totalQuestions: 20,
  },
  {
    id: "job-2025-agri-info-office-asst",
    ministry: "কৃষি তথ্য সার্ভিস",
    post: "কম্পিউটার অপারেটর/অফিস সহকারী",
    date: "2025-08-09",
    duration: "৯০ মিনিট",
    totalMarks: 95,
    totalQuestions: 13,
  },
  {
    id: "job-2025-expatriate-welfare-steno",
    ministry: "প্রবাসী কল্যাণ ও বৈদেশিক কর্মসংস্থান মন্ত্রণালয়",
    post: "সাঁট মুদ্রাক্ষরিক কাম কম্পিউটার অপারেটর",
    date: "2025-07-25",
    duration: "৯০ মিনিট",
    totalMarks: 90,
    totalQuestions: 15,
  },
  {
    id: "job-2025-nipor-steno",
    ministry: "জাতীয় জনসংখ্যা গবেষণা ও প্রশিক্ষণ ইনস্টিটিউট",
    post: "সাঁট মুদ্রাক্ষরিক কাম কম্পিউটার অপারেটর",
    date: "2025-07-25",
    duration: "৯০ মিনিট",
    totalMarks: 70,
    totalQuestions: 12,
  },
  {
    id: "job-2025-btmc-sub-asst-engineer-civil",
    ministry: "বাংলাদেশ টেক্সটাইল মিলস কর্পোরেশন",
    post: "উপ সহকারী প্রকৌশলী (পুর)",
    date: "2025-07-25",
    duration: "৯০ মিনিট",
    totalMarks: 32,
    totalQuestions: 6,
  },
  {
    id: "job-2025-biwta-shulko-adaykari",
    ministry: "বাংলাদেশ অভ্যন্তরীণ নৌ-পরিবহন কর্তৃপক্ষ",
    post: "শুল্ক আদায়কারী",
    date: "2025-07-25",
    duration: "৯০ মিনিট",
    totalMarks: 45,
    totalQuestions: 4,
  },
  {
    id: "job-2025-archives-library-office-shohayok",
    ministry: "আরকাইভস ও গ্রন্থাগার অধিদপ্তর",
    post: "অফিস সহায়ক",
    date: "2025-07-25",
    duration: "৬০ মিনিট",
    totalMarks: 70,
    totalQuestions: 12,
  },
  {
    id: "job-2025-probashi-kollan-office-sohayok",
    ministry: "প্রবাসী কল্যাণ ও বৈদেশিক কর্মসংস্থান মন্ত্রণালয়",
    post: "অফিস সহকারী/সাঁট মুদ্রাক্ষরিক",
    date: "2025-08-01",
    duration: "৯০ মিনিট",
    totalMarks: 90,
    totalQuestions: 14,
  },
  {
    id: "job-2025-janaprashasan-office-sohayok-cum-mudrakkhorik",
    ministry: "জনপ্রশাসন মন্ত্রণালয়",
    post: "অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-08-01",
    duration: "৯০ মিনিট",
    totalMarks: 90,
    totalQuestions: 15,
  },
  {
    id: "job-2025-janaprashasan-hisab-rakkhok",
    ministry: "জনপ্রশাসন মন্ত্রণালয়",
    post: "হিসাব রক্ষক",
    date: "2025-08-01",
    duration: "৯০ মিনিট",
    totalMarks: 100,
    totalQuestions: 17,
  },
  {
    id: "job-2025-biwta-stenographer-pa",
    ministry: "বাংলাদেশ অভ্যন্তরীণ নৌ-পরিবহন কর্তৃপক্ষ",
    post: "সাঁটলিপিকার (ব্যক্তিগত সহকারী)",
    date: "2025-07-25",
    duration: "১২০ মিনিট",
    totalMarks: 77,
    totalQuestions: 8,
  },
  {
    id: "job-2025-sparrso-office-sohayok",
    ministry: "মহাকাশ গবেষণা ও দূর অনুধাবন প্রতিষ্ঠান (স্পারসো)",
    post: "অফিস সহায়ক",
    date: "2025-08-09",
    duration: "৬০ মিনিট",
    totalMarks: 44,
    totalQuestions: 12,
  },
  {
    id: "job-2025-bab-office-asst-typist",
    ministry: "বাংলাদেশ অ্যাক্রেডিটেশন কাউন্সিল, ঢাকা",
    post: "অফিস সহকারী কাম কম্পিউটার মুদ্রাক্ষরিক",
    date: "2025-08-16",
    duration: "৯০ মিনিট",
    totalMarks: 75,
    totalQuestions: 10,
  },
  // পরবর্তী পরীক্ষা এখানে যোগ করুন
];
