// exam-archive.js — পরীক্ষার তালিকা
// প্রতিটা exam-এর id, job-solution.js এর id prefix-এর সাথে মিলতে হবে।

const EXAM_ARCHIVE = [
  {
    id: "job-2025-dc",
    ministry: "জেলা প্রশাসকের কার্যালয়, জয়পুরহাট",
    post: "নাজির কাম ক্যাশিয়ার / সার্টিফিকেট পেশকার",
    date: "2025-06-27",
    duration: "৯০ মিনিট",
    totalMarks: 100,
    totalQuestions: 15,
  },
  {
    id: "job-2025-tech-edu-keeper",
    ministry: "কারিগরি শিক্ষা অধিদপ্তর",
    post: "সহকারী কাম কিপার",
    date: "2025-07-04",
    duration: "৯০ মিনিট",
    totalMarks: 90,
    totalQuestions: 34,
  },
  {
    id: "job-2025-tech-edu-driver",
    ministry: "কারিগরি শিক্ষা অধিদপ্তর",
    post: "ড্রাইভার কাম মেকানিক",
    date: "2025-07-04",
    duration: "৯০ মিনিট",
    totalMarks: 90,
    totalQuestions: 34,
  },
  {
    id: "job-2025-tech-edu-steno",
    ministry: "কারিগরি শিক্ষা অধিদপ্তর",
    post: "সাঁটলিপিকার কাম-কম্পিউটার অপারেটর",
    date: "2025-07-04",
    duration: "৯০ মিনিট",
    totalMarks: 90,
    totalQuestions: 34,
  },
  {
    id: "job-2025-iwta-traffic",
    ministry: "অভ্যন্তরীণ নৌ পরিবহন কর্তৃপক্ষ",
    post: "ট্রাফিক সুপারভাইজার",
    date: "2025-07-04",
    duration: "৯০ মিনিট",
    totalMarks: 90,
    totalQuestions: 6,
  },
  {
    id: "job-2025-dc-bhola",
    ministry: "জেলা প্রশাসকের কার্যালয়, ভোলা",
    post: "অফিস সহায়ক/নিরাপত্তা প্রহরী",
    date: "2025-07-05",
    duration: "৮০ মিনিট",
    totalMarks: 80,
    totalQuestions: 20,
  },
  {
    id: "job-2025-coast-guard-uhs",
    ministry: "বাংলাদেশ কোস্ট গার্ড",
    post: "উচ্চমান সহকারী",
    date: "2025-07-05",
    duration: "৯০ মিনিট",
    totalMarks: 90,
    totalQuestions: 12,
  },
  {
    id: "job-2025-navy-office",
    ministry: "বাংলাদেশ নৌ বাহিনী",
    post: "অফিস সহকারী কাম-কম্পিউটার অপারেটর",
    date: "2025-07-11",
    duration: "৯০ মিনিট",
    totalMarks: 70,
    totalQuestions: 28,
  },
  {
    id: "job-2025-coast-guard-support",
    ministry: "বাংলাদেশ কোস্ট গার্ড",
    post: "অফিস সহায়ক",
    date: "2025-07-12",
    duration: "৬০ মিনিট",
    totalMarks: 90,
    totalQuestions: 13,
  },
  {
    id: "job-2025-hbfc-data-entry",
    ministry: "বাংলাদেশ হাউজ বিল্ডিং ফাইন্যান্স কর্পোরেশন",
    post: "ডাটা এন্ট্রি অপারেটর",
    date: "2025-07-18",
    duration: "৬০ মিনিট",
    totalMarks: 90,
    totalQuestions: 10,
  },
  // পরবর্তী পরীক্ষা এখানে যোগ করুন
];